#### Data set feature engineering

Dataset: 
 
 - _music_clean.csv_ 

Author: Luis Sergio Pastrana Lemus  
Date: 2025-04-23

# Feature Engineering  – Music Activity Dataset

## __1. Libraries__

In [16]:
from IPython.display import display, HTML
import os
import pandas as pd
from pathlib import Path
import sys

# Define project root dynamically, gets the current directory from whick the notebook belongs and moves one level upper
project_root = Path.cwd().parent

# Add src to sys.path if it is not already
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Import function directly (more controlled than import *)
from src import *

## __2. Path to Data file__

In [17]:
# Build route to data file and upload
data_file_path = project_root / "data" / "processed"
df_music_clean = load_dataset_from_csv(data_file_path, "music_clean.csv", sep=',', header='infer')

In [18]:
# Format notebook output
format_notebook()

## 3 __Casting to data types__

### **3.1** Casting Data Types

#### **3.1.1** Casting to category datatype

In [19]:
# Casting to category dtype 
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['genre'])
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['city'])
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['day'])

#### **3.1.2** Casting to datetime data type

In [20]:
# Casting to datetime dtype 
df_music_clean = cast_datatypes(df_music_clean, 'datetime', date_format="%H:%M:%S", c_include=['time'])

In [21]:
df_music_clean

         userid                           track            artist       genre         city      time        day
0      FFB692EC               kamigata_to_boots  the_mass_missile        rock  shelbyville  20:28:33  wednesday
1      55204538     delayed_because_of_accident  andreas_ronnberg        rock  springfield  14:07:09     friday
2        20EC38               funiculi_funicula       mario_lanza         pop  shelbyville  20:58:07  wednesday
3      A3DD03C9           dragons_in_the_sunset          fire_ice        folk  shelbyville  08:37:09     monday
4      E2DC1FAE                     soul_people        space_echo       dance  springfield  08:34:34     monday
...         ...                             ...               ...         ...          ...       ...        ...
59957  729CBB09                         my_name            mclean         rnb  springfield  13:32:28  wednesday
59958  D08D4A55  maybe_one_day_feat_black_spade         blu_exile      hiphop  shelbyville  10:00:00     monday
59959  C5E3A0D5                       jalopiina           unknown  industrial  springfield  20:09:26     friday
59960  321D0506                   freight_train     chas_mcdevitt        rock  springfield  21:43:59     friday
59961  3A64EF84       tell_me_sweet_little_lies      monica_lopez     country  springfield  21:59:46     friday

[59962 rows x 7 columns]

In [22]:
df_music_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59962 entries, 0 to 59961
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userid  59962 non-null  object
 1   track   59962 non-null  object
 2   artist  59962 non-null  object
 3   genre   59962 non-null  category
 4   city    59962 non-null  category
 5   time    59962 non-null  object
 6   day     59962 non-null  category
dtypes: category(3), object(4)
memory usage: 2.1+ MB

In [23]:
type(df_music_clean['time'].iloc[0])

datetime.time

## 4. Feature Engineering

### **4.1** Original Dataset Feature Engineering

In [24]:
df_music_clean

         userid                           track            artist       genre         city      time        day
0      FFB692EC               kamigata_to_boots  the_mass_missile        rock  shelbyville  20:28:33  wednesday
1      55204538     delayed_because_of_accident  andreas_ronnberg        rock  springfield  14:07:09     friday
2        20EC38               funiculi_funicula       mario_lanza         pop  shelbyville  20:58:07  wednesday
3      A3DD03C9           dragons_in_the_sunset          fire_ice        folk  shelbyville  08:37:09     monday
4      E2DC1FAE                     soul_people        space_echo       dance  springfield  08:34:34     monday
...         ...                             ...               ...         ...          ...       ...        ...
59957  729CBB09                         my_name            mclean         rnb  springfield  13:32:28  wednesday
59958  D08D4A55  maybe_one_day_feat_black_spade         blu_exile      hiphop  shelbyville  10:00:00     monday
59959  C5E3A0D5                       jalopiina           unknown  industrial  springfield  20:09:26     friday
59960  321D0506                   freight_train     chas_mcdevitt        rock  springfield  21:43:59     friday
59961  3A64EF84       tell_me_sweet_little_lies      monica_lopez     country  springfield  21:59:46     friday

[59962 rows x 7 columns]

In [25]:
df_music_featured = df_music_clean.copy()
df_music_featured['hour'] = df_music_featured['time'].apply(lambda x: x.hour if pd.notnull(x) else None)
df_music_featured

         userid                           track            artist       genre         city      time        day  hour
0      FFB692EC               kamigata_to_boots  the_mass_missile        rock  shelbyville  20:28:33  wednesday    20
1      55204538     delayed_because_of_accident  andreas_ronnberg        rock  springfield  14:07:09     friday    14
2        20EC38               funiculi_funicula       mario_lanza         pop  shelbyville  20:58:07  wednesday    20
3      A3DD03C9           dragons_in_the_sunset          fire_ice        folk  shelbyville  08:37:09     monday     8
4      E2DC1FAE                     soul_people        space_echo       dance  springfield  08:34:34     monday     8
...         ...                             ...               ...         ...          ...       ...        ...   ...
59957  729CBB09                         my_name            mclean         rnb  springfield  13:32:28  wednesday    13
59958  D08D4A55  maybe_one_day_feat_black_spade         blu_exile      hiphop  shelbyville  10:00:00     monday    10
59959  C5E3A0D5                       jalopiina           unknown  industrial  springfield  20:09:26     friday    20
59960  321D0506                   freight_train     chas_mcdevitt        rock  springfield  21:43:59     friday    21
59961  3A64EF84       tell_me_sweet_little_lies      monica_lopez     country  springfield  21:59:46     friday    21

[59962 rows x 8 columns]

### **4.2** Dataset Segmentation

In [26]:
# Get Location segmentation
df_music_location = df_music_clean.groupby(['city', 'userid'], observed=True).agg(tracks=('track', 'nunique'), artists=('artist', 'nunique'), genres=('genre', 'nunique'))
df_music_location = df_music_location.reset_index()
df_music_location

              city    userid  tracks  artists  genres
0      shelbyville  100173ED       1        1       1
1      shelbyville  10089377       3        3       2
2      shelbyville  10101201       2        2       2
3      shelbyville  101861D1       2        2       2
4      shelbyville  10189D10       4        3       2
...            ...       ...     ...      ...     ...
41345  springfield  FFF91C68       1        1       1
41346  springfield  FFF92382       1        1       1
41347  springfield  FFF965B2       2        2       2
41348  springfield   FFFBB52       4        4       4
41349  springfield   FFFD03A       1        1       1

[41350 rows x 5 columns]

In [27]:
# Get Location and datetime segmentation
df_music_loc_dt = df_music_featured.groupby(['city', 'userid', 'day', 'hour'], observed=True).agg(tracks=('track', 'nunique'), artists=('artist', 'nunique'), genres=('genre', 'nunique'))
df_music_loc_dt = df_music_loc_dt.reset_index()
df_music_loc_dt

              city    userid        day  hour  tracks  artists  genres
0      shelbyville  100173ED  wednesday    20       1        1       1
1      shelbyville  10089377     monday    20       1        1       1
2      shelbyville  10089377  wednesday    21       2        2       2
3      shelbyville  10101201  wednesday    14       2        2       2
4      shelbyville  101861D1     monday    20       2        2       2
...            ...       ...        ...   ...     ...      ...     ...
49839  springfield  FFF92382     monday     9       1        1       1
49840  springfield  FFF965B2     monday    13       1        1       1
49841  springfield  FFF965B2     monday    14       1        1       1
49842  springfield   FFFBB52     monday    20       4        4       4
49843  springfield   FFFD03A     friday    20       1        1       1

[49844 rows x 7 columns]

In [28]:
project_root = Path.cwd().parent
processed_path = project_root / "data" / "processed" / "music_featured.csv"
df_music_featured.to_csv(processed_path, index=False)

In [29]:
project_root = Path.cwd().parent
processed_path = project_root / "data" / "processed" / "music_location.csv"
df_music_location.to_csv(processed_path, index=False)

In [30]:
project_root = Path.cwd().parent
processed_path = project_root / "data" / "processed" / "music_location_datetime.csv"
df_music_loc_dt.to_csv(processed_path, index=False)