#### Data set feature engineering

Dataset: 
 
 - _music_clean.csv_ 
 - _music_location.csv_
 - _music_location_datetime_.csv

Author: Luis Sergio Pastrana Lemus  
Date: 2025-04-23

# Dataset Shape and Dispersion

## __1. Libraries__

In [1]:
from IPython.display import display, HTML
import os
import pandas as pd
from pathlib import Path
import sys

# Define project root dynamically, gets the current directory from whick the notebook belongs and moves one level upper
project_root = Path.cwd().parent

# Add src to sys.path if it is not already
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Import function directly (more controlled than import *)
from src import *

## __2. Path to Data file__

In [2]:
# Build route to data file and upload
data_file_path = project_root / "data" / "processed"
df_music_clean = load_dataset_from_csv(data_file_path, "music_clean.csv", sep=',', header='infer')
df_music_location = load_dataset_from_csv(data_file_path, "music_location.csv", sep=',', header='infer')
df_music_loc_dt = load_dataset_from_csv(data_file_path, "music_location_datetime.csv", sep=',', header='infer')

In [3]:
# Format notebook output
format_notebook()

## __3. Casting to data types__

### **3.0** Casting Data Types

#### **3.0.1** Casting to category datatype

In [4]:
# Casting to category dtype 
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['genre'])
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['city'])
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['day'])

#### **3.0.2** Casting to datetime data type

In [5]:
# Casting to datetime dtype 
df_music_clean = cast_datatypes(df_music_clean, 'datetime', date_format="%H:%M:%S", c_include=['time'])

In [6]:
df_music_clean

         userid                           track            artist       genre         city      time        day
0      FFB692EC               kamigata_to_boots  the_mass_missile        rock  shelbyville  20:28:33  wednesday
1      55204538     delayed_because_of_accident  andreas_ronnberg        rock  springfield  14:07:09     friday
2        20EC38               funiculi_funicula       mario_lanza         pop  shelbyville  20:58:07  wednesday
3      A3DD03C9           dragons_in_the_sunset          fire_ice        folk  shelbyville  08:37:09     monday
4      E2DC1FAE                     soul_people        space_echo       dance  springfield  08:34:34     monday
...         ...                             ...               ...         ...          ...       ...        ...
59957  729CBB09                         my_name            mclean         rnb  springfield  13:32:28  wednesday
59958  D08D4A55  maybe_one_day_feat_black_spade         blu_exile      hiphop  shelbyville  10:00:00     monday
59959  C5E3A0D5                       jalopiina           unknown  industrial  springfield  20:09:26     friday
59960  321D0506                   freight_train     chas_mcdevitt        rock  springfield  21:43:59     friday
59961  3A64EF84       tell_me_sweet_little_lies      monica_lopez     country  springfield  21:59:46     friday

[59962 rows x 7 columns]

In [7]:
df_music_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59962 entries, 0 to 59961
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userid  59962 non-null  object
 1   track   59962 non-null  object
 2   artist  59962 non-null  object
 3   genre   59962 non-null  category
 4   city    59962 non-null  category
 5   time    59962 non-null  object
 6   day     59962 non-null  category
dtypes: category(3), object(4)
memory usage: 2.1+ MB

In [8]:
type(df_music_clean['time'].iloc[0])

datetime.time

## __4. Distribution and Outliers__

In [9]:
# df_music_clean.columns

# evaluate_central_trend(df, column)

# outlier_limit_bounds(df, column, bound='both', clamp_zero=False)

# evaluate_correlation(df, columns=None)

In [ ]:
plotly_frequency_density_numeric_plotlypx(df_music_location['tracks'], bins=50, density=False, color='grey', title='Global Tracks Distribution', xlabel='Tracks', ylabel='Frequency/Density',
                                          xticks_range=(0, 50, 1), rotation=0, show_kde=False)

In [ ]:
plotly_frequency_density_numeric_plotlypx(df_music_location['artists'], bins=40, density=False, color='grey', title='Global Artists Distribution', xlabel='Artists', ylabel='Frequency/Density',
                                          xticks_range=(0, 40, 1), rotation=0, show_kde=False)

In [ ]:
plotly_frequency_density_numeric_plotlypx(df_music_location['genres'], bins=18, density=False, color='grey', title='Global Genres Distribution', xlabel='Genres', ylabel='Frequency/Density',
                                          xticks_range=(0, 18, 1), rotation=0, show_kde=False)

In [ ]:
plotly_frequency_density_numeric_plotlypx(df_music_loc_dt['day'], bins=7, density=False, color='grey', title='Global Tracks Distribution By Day', xlabel='Days', ylabel='Frequency/Density',
                                          xticks_range=(1,7,1), rotation=0, show_kde=False)

In [ ]:
plotly_frequency_density_numeric_plotlypx(df_music_loc_dt['hour'], bins=24, density=False, color='grey', title='Global Tracks Distribution By Hour', xlabel='Hours', ylabel='Frequency/Density',
                                          xticks_range=(0, 24, 1), rotation=0, show_kde=False)

### **4.2** Outliers evaluation

#### **4.2.1** Outliers

In [19]:
outlier_limit_bounds(df_music_location, 'tracks', bound='both', clamp_zero=True, verbose=True)

              city    userid  tracks  artists  genres
4      shelbyville  10189D10       4        3       2
11     shelbyville  102A0499       5        5       4
15     shelbyville  1049FBE1       7        6       6
16     shelbyville  104B7BA5       4        4       2
115    shelbyville  12329DEF       6        6       2
...            ...       ...     ...      ...     ...
41277  springfield  FF710BD9      11       11       5
41286  springfield  FF8287BB      17       17       4
41309  springfield  FFBE3E18       8        8       2
41321  springfield  FFD1A16F       6        6       2
41348  springfield   FFFBB52       4        4       4

[1612 rows x 5 columns]

In [21]:
outlier_limit_bounds(df_music_location, 'artists', bound='both', clamp_zero=True, verbose=True)

              city    userid  tracks  artists  genres
11     shelbyville  102A0499       5        5       4
15     shelbyville  1049FBE1       7        6       6
16     shelbyville  104B7BA5       4        4       2
115    shelbyville  12329DEF       6        6       2
217    shelbyville  13EF647B       4        4       3
...            ...       ...     ...      ...     ...
41277  springfield  FF710BD9      11       11       5
41286  springfield  FF8287BB      17       17       4
41309  springfield  FFBE3E18       8        8       2
41321  springfield  FFD1A16F       6        6       2
41348  springfield   FFFBB52       4        4       4

[1596 rows x 5 columns]

In [23]:
outlier_limit_bounds(df_music_location, 'genres', bound='both', clamp_zero=True, verbose=True)

              city    userid  tracks  artists  genres
11     shelbyville  102A0499       5        5       4
15     shelbyville  1049FBE1       7        6       6
92     shelbyville  11D3698F       3        3       3
217    shelbyville  13EF647B       4        4       3
230    shelbyville  1442051A       4        4       3
...            ...       ...     ...      ...     ...
41277  springfield  FF710BD9      11       11       5
41286  springfield  FF8287BB      17       17       4
41295  springfield   FF9C157       3        3       3
41312  springfield  FFC96562       3        3       3
41348  springfield   FFFBB52       4        4       4

[2129 rows x 5 columns]

In [30]:
outlier_limit_bounds(df_music_loc_dt, 'day', bound='both', clamp_zero=True, verbose=False)

In [33]:
outlier_limit_bounds(df_music_loc_dt, 'hour', bound='both', clamp_zero=True, verbose=False)

#### **4.2.2** Outliers and Data Dispersion Visualization

In [24]:
plot_horizontal_boxplot_plotlypx(df_music_location, 'tracks', title='Outliers and Data Dispersion for Tracks')

In [25]:
plot_horizontal_boxplot_plotlypx(df_music_location, 'artists', title='Outliers and Data Dispersion for Artists')

In [26]:
plot_horizontal_boxplot_plotlypx(df_music_location, 'genres', title='Outliers and Data Dispersion for Genres')

In [27]:
plot_horizontal_boxplot_plotlypx(df_music_loc_dt, 'day', title='Outliers and Data Dispersion for Days')

In [34]:
plot_horizontal_boxplot_plotlypx(df_music_loc_dt, 'hour', title='Outliers and Data Dispersion for Hours')